apiVersion: apps/v1
kind: Deployment
metadata:
   name: DEPLOYMENT_NAME-NAMESPACE
   namespace: NAMESPACE-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENT_NAME-NAMESPACE
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: DEPLOYMENT_NAME-NAMESPACE
    spec:
      containers:
      - name: DEPLOYMENT_NAME-NAMESPACE
        image: dockerImageName
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-sc
                key: openai-sc
          - name: FIREBASE_DATABASE_COLLECTION
            value: NAMESPACE-env
        ports:
        - containerPort: 5004

---
apiVersion: v1
kind: Service
metadata:
  name: DEPLOYMENT_NAME-NAMESPACE
  namespace: NAMESPACE-env
  labels:
    app: DEPLOYMENT_NAME-NAMESPACE
spec:
  selector:
    app: DEPLOYMENT_NAME-NAMESPACE
  ports:
    - name: http
      port: 80
      targetPort: 5004
  type: ClusterIP