apiVersion: apps/v1
kind: Deployment
metadata:
   name: imageapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageapi
  template:
    metadata:
      labels:
        app: imageapi
    spec:
      containers:
      - name: imageapi
        image: shehan97105/imageservice:latest
        ports:
        - containerPort: 5004

---
apiVersion: v1
kind: Service
metadata:
  name: imageapi
  labels:
    app: imageapi
spec:
  selector:
    type: NodePort
    app: imageapi
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004